{
  imports = [
    ./audio.nix
    ./illuminanced.nix
    ./dbus.nix
    ./journald.nix
    ./xserver.nix
    ./ssh.nix
    ./printing.nix
    ./lightdm.nix
    ./sddm.nix
    ./syncthing.nix
    ./hypridle.nix
    ./wivrn.nix
    ./envfs.nix
    ./power-management.nix
    ./clamav.nix
    ./usbguard.nix
  ];
}
